<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-26T18:29:34 EDT" name="Default suite" finished-at="2023-06-26T18:29:44 EDT" duration-ms="10376">
    <groups>
      <group name="SMOKE">
        <method signature="Test101.testOrangeHRM()[pri:2, instance:extentReport.Extent_Report_ThreadSafe.Test101@188715b5]" name="testOrangeHRM" class="extentReport.Extent_Report_ThreadSafe.Test101"/>
      </group> <!-- SMOKE -->
    </groups>
    <test started-at="2023-06-26T18:29:34 EDT" name="Default test" finished-at="2023-06-26T18:29:44 EDT" duration-ms="10376">
      <class name="extentReport.Extent_Report_ThreadSafe.Test101">
        <test-method is-config="true" signature="setup()[pri:0, instance:extentReport.Extent_Report_ThreadSafe.Test101@188715b5]" started-at="2023-06-26T18:29:34 EDT" name="setup" finished-at="2023-06-26T18:29:36 EDT" duration-ms="2164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testGoogle()[pri:0, instance:extentReport.Extent_Report_ThreadSafe.Test101@188715b5]" started-at="2023-06-26T18:29:36 EDT" name="testGoogle" description="TC 101" finished-at="2023-06-26T18:29:38 EDT" duration-ms="2059" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is miss-matched expected [HYR Tutorials - Google Search] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is miss-matched expected [HYR Tutorials - Google Search] but found [Google]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at extentReport.Extent_Report_ThreadSafe.Test101.testGoogle(Test101.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoogle -->
        <test-method signature="testFacebook()[pri:1, instance:extentReport.Extent_Report_ThreadSafe.Test101@188715b5]" started-at="2023-06-26T18:29:38 EDT" name="testFacebook" description="TC 102" finished-at="2023-06-26T18:29:40 EDT" duration-ms="1796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFacebook -->
        <test-method signature="testOrangeHRM()[pri:2, instance:extentReport.Extent_Report_ThreadSafe.Test101@188715b5]" started-at="2023-06-26T18:29:40 EDT" name="testOrangeHRM" description="TC 103" finished-at="2023-06-26T18:29:44 EDT" duration-ms="3965" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title miss-matched expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title miss-matched expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at extentReport.Extent_Report_ThreadSafe.Test101.testOrangeHRM(Test101.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOrangeHRM -->
        <test-method signature="testNaveenAutomation()[pri:3, instance:extentReport.Extent_Report_ThreadSafe.Test101@188715b5]" started-at="2023-06-26T18:29:44 EDT" name="testNaveenAutomation" description="TC 444" finished-at="2023-06-26T18:29:44 EDT" depends-on-methods="extentReport.Extent_Report_ThreadSafe.Test101.testOrangeHRM" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method extentReport.Extent_Report_ThreadSafe.Test101.testNaveenAutomation() on instance extentReport.Extent_Report_ThreadSafe.Test101@188715b5 depends on not successfully finished methods 
[extentReport.Extent_Report_ThreadSafe.Test101.testOrangeHRM() on instance extentReport.Extent_Report_ThreadSafe.Test101@188715b5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method extentReport.Extent_Report_ThreadSafe.Test101.testNaveenAutomation() on instance extentReport.Extent_Report_ThreadSafe.Test101@188715b5 depends on not successfully finished methods 
[extentReport.Extent_Report_ThreadSafe.Test101.testOrangeHRM() on instance extentReport.Extent_Report_ThreadSafe.Test101@188715b5]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNaveenAutomation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:extentReport.Extent_Report_ThreadSafe.Test101@188715b5]" started-at="2023-06-26T18:29:44 EDT" name="tearDown" finished-at="2023-06-26T18:29:44 EDT" duration-ms="118" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReport.Extent_Report_ThreadSafe.Test101 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
